# Use the latest version of Nginx
FROM nginx:latest

# Copy the custom configuration file to the appropriate location in the container
COPY proxy.conf /etc/nginx/conf.d/default.conf

# Expose port 80 to allow traffic
EXPOSE 80
